spring:
  application:
    name: gestao_vagas

  datasource:
    url: jdbc:postgresql://localhost:5433/gestao_vagas
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    token:
      secret: "JavaSecret"
      candidate: "JavaSecretCandidate"
